### ISSUE TITLE
Can't move PolyToolkit into a Plugins directory

### ISSUE THREAD

**Issue by Zenopheus** [googlevr/poly-toolkit-unity#11]
Like many Unity projects we store all 3rd party assets in a sub directory under the "Plugins" directory to avoid polluting our directory structure and improve build times. When I do this with PolyToolkit it becomes disabled and displays "Your project seems to be using internal Poly Toolkit classes".

**Comment by iBicha** [comment]
That's not the best practice, Unity has a specific use of the folder "Plugins"
https://docs.unity3d.com/Manual/Plugins.html
(Unrelated to the issue, which is can't move polytoolkit)

**Comment by btco** [comment]
PolyToolkit can't be easily moved from Assets/PolyToolkit because there are some hard-coded paths:

- AssetBrowserWindow has hard-coded paths to textures
- Shaders files have hard-coded paths to cginc files in Assets/PolyToolkit
- WarnAboutUsingPolyInternal knows not to check a file because its path contains "Assets/PolyToolkit".

These are all addressable. I'll see what I can do!

**Comment by btco** [comment]
Fixed. Users can now move PolyToolkit to whichever folder they want under Assets.

**Comment by btco** [comment]
TIP: Some Unity versions have an issue where, after moving Poly Toolkit to a different folder, you will get error messages like this:

```
Shader error in 'Brush/DiffuseSingleSided': failed to open source file: '../../../Shaders/Include/Brush.cginc' at line 30 (on d3d11)
```
(and similar)

Restarting Unity does NOT solve it.
The solution is to reimport all shaders.
This can be done by right-clicking the PolyToolkit folder and selecting Reimport.

**Comment by Zenopheus** [comment]
Thank you!
