### ISSUE TITLE
Unity version support is seriously outdated

### ISSUE THREAD

**Issue by andybak** [googlevr/poly-toolkit-unity#12]
The warning message says 5.6.x I could understand not supporting 2018 yet but surely Unity 2017 is a fairly reasonable baseline? 2017.4 is the current LTS release after all.

**Comment by btco** [comment]
Not sure I understood correctly, but, to clarify, Poly Toolkit supports 5.6 _or later_.

If you want to use Poly Toolkit as a _user_ (i.e., not as a developer of Poly Toolkit itself), it's best to download the pre-built packages:

https://github.com/googlevr/poly-toolkit-unity/releases

However, if you want to work on the Poly Toolkit code itself (a much rarer case), then you have to use exactly 5.6.3, because it's safer to develop with the minimum version in order to ensure nothing breaks for users.
