### ISSUE TITLE
Feature Request: Browse local offline Google Blocks files

### ISSUE THREAD

**Issue by philmaas** [googlevr/poly-toolkit-unity#3]
It would be great to be able to browse and import models saved in a user defined location or the default Google Blocks folder  C:\Users\User\Documents\Blocks\OfflineModels

There seems to be an issue with signing in with Google Blocks to the Poly website to publish models.
This offline feature would prevent people from being blocked by bugs and web issues like that and they could keep working and importing assets to unity without having to publish first.

**Comment by btco** [comment]
Blocks wasn't really designed for offline use (OfflineModels exists solely for internal caching/backup purposes and is not meant to be used directly). In fact, OfflineModels is in a proprietary Blocks-only format while Poly Toolkit can only use GLTF, which is the standard for Poly, so for now there's really no way to bypass the cloud in this case.

Preemptive counter-argument: but why doesn't Blocks save to a local GLTF file that Poly Toolkit can pick up?

Preemptive response to preemptive counter-argument: Because the GLTF that Blocks produces isn't necessarily the same GLTF that Poly serves. Poly Toolkit benefits from server-side processing done by the Poly server, which wouldn't happen in the offline use case.
